Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|    
      master.vm.box = "bento/ubuntu-16.04"
      master.vm.network :private_network, ip: "192.168.56.100"
      master.vm.hostname = "master"
      master.vm.synced_folder "shared", "/home/vagrant/projects"
      master.vm.provision "shell", path: "config-ansible.sh"
      master.vm.provider  "virtualbox" do |v|
          v.name = "master"
          v.memory = 512
          v.cpus = 1
      end
  end
end