Vagrant.configure("2") do |config|
    config.vm.define "jenkins" do |nodo1|
        nodo1.vm.box = "bento/ubuntu-16.04"
        nodo1.vm.network :private_network, ip: "192.168.56.161"
        nodo1.vm.hostname = "jenkins"
        nodo1.vm.provider  "virtualbox" do |v|
            v.name = "jenkins"
            v.memory = 512
            v.cpus = 1
        end    
    end
end